### ISSUE TITLE
The environment problem.

### ISSUE THREAD

**Issue by conquer-pan** [SAIS-FUXI/EvalAlign#2]
[2024-07-05 11:14:35,572] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)
 [WARNING]  async_io requires the dev libaio .so object and headers but these were not found.
 [WARNING]  async_io: please install the libaio-devel package with yum
 [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
 [WARNING]  Please specify the CUTLASS repo directory as environment variable $CUTLASS_PATH
 [WARNING]  sparse_attn requires a torch version >= 1.5 and < 2.0 but detected 2.1
 [WARNING]  using untested triton version (2.1.0), only 1.0.0 is known to be compatible
Traceback (most recent call last):
  File "/home/nas01/panjiahao1/eval/EvalAlign-main/evalalign/eval/test_faithfulness.py", line 8, in <module>
    from evalalign.constants import (
  File "/home/nas01/panjiahao1/eval/EvalAlign-main/evalalign/__init__.py", line 1, in <module>
    from .model import LlavaLlamaForCausalLM
ImportError: cannot import name 'LlavaLlamaForCausalLM' from 'evalalign.model'

what can i do for this?

**Comment by SAIS-FUXI** [comment]
Have you tried the "pip install - e." command before? It is recommended to rebuild the environment

**Comment by SAIS-FUXI** [comment]
> [2024-07-05 11:14:35,572] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect) [WARNING] async_io requires the dev libaio .so object and headers but these were not found. [WARNING] async_io: please install the libaio-devel package with yum [WARNING] If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found. [WARNING] Please specify the CUTLASS repo directory as environment variable $CUTLASS_PATH [WARNING] sparse_attn requires a torch version >= 1.5 and < 2.0 but detected 2.1 [WARNING] using untested triton version (2.1.0), only 1.0.0 is known to be compatible Traceback (most recent call last): File "/home/nas01/panjiahao1/eval/EvalAlign-main/evalalign/eval/test_faithfulness.py", line 8, in from evalalign.constants import ( File "/home/nas01/panjiahao1/eval/EvalAlign-main/evalalign/**init**.py", line 1, in from .model import LlavaLlamaForCausalLM ImportError: cannot import name 'LlavaLlamaForCausalLM' from 'evalalign.model'
> 
> what can i do for this?

Have you tried the "pip install - e." command before? It is recommended to rebuild the environment

**Comment by conquer-pan** [comment]
> > [2024-07-05 11:14:35,572] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect) [WARNING] async_io requires the dev libaio .so object and headers but these were not found. [WARNING] async_io: please install the libaio-devel package with yum [WARNING] If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found. [WARNING] Please specify the CUTLASS repo directory as environment variable $CUTLASS_PATH [WARNING] sparse_attn requires a torch version >= 1.5 and < 2.0 but detected 2.1 [WARNING] using untested triton version (2.1.0), only 1.0.0 is known to be compatible Traceback (most recent call last): File "/home/nas01/panjiahao1/eval/EvalAlign-main/evalalign/eval/test_faithfulness.py", line 8, in from evalalign.constants import ( File "/home/nas01/panjiahao1/eval/EvalAlign-main/evalalign/**init**.py", line 1, in from .model import LlavaLlamaForCausalLM ImportError: cannot import name 'LlavaLlamaForCausalLM' from 'evalalign.model'
> > what can i do for this?
> 
> Have you tried the "pip install - e." command before? It is recommended to rebuild the environment

![image](https://github.com/SAIS-FUXI/EvalAlign/assets/91402007/165c02bd-4d17-48c8-b9bf-0651b7c7c1bc)
I start with "pip install torch==2.1.2 torchvision==0.16.2 torchaudio==2.1.2 --index-url https://download.pytorch.org/whl/cu118 "instructions to install the torch, and then use" PIP install - e." to install evalalign. However, the above problems still occur. Is evalalign not installed yet?
